# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pidMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pidMenu(object):
    def setupUi(self, pidMenu):
        pidMenu.setObjectName("pidMenu")
        pidMenu.resize(675, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pidMenu.sizePolicy().hasHeightForWidth())
        pidMenu.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        #palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        #palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.532338, 0.0, 0.526975, 0.864)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(103, 103, 103))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        #palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        pidMenu.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        pidMenu.setFont(font)
        pidMenu.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.532338, y1:0, x2:0.526975, y2:0.864, stop:0 rgba(103, 103, 103, 255), stop:1 rgba(0, 0, 0, 255));\n"
"color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.mainVals = QtWidgets.QWidget()
        self.mainVals.setObjectName("mainVals")
        self.depth = QtWidgets.QLabel(self.mainVals)
        self.depth.setGeometry(QtCore.QRect(270, 190, 141, 30))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.depth.setFont(font)
        self.depth.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.depth.setObjectName("depth")
        self.roll = QtWidgets.QLabel(self.mainVals)
        self.roll.setGeometry(QtCore.QRect(280, 30, 91, 30))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.roll.setFont(font)
        self.roll.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.roll.setObjectName("roll")
        self.pitch = QtWidgets.QLabel(self.mainVals)
        self.pitch.setGeometry(QtCore.QRect(270, 360, 111, 30))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pitch.setFont(font)
        self.pitch.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pitch.setObjectName("pitch")
        self.rollp = QtWidgets.QLabel(self.mainVals)
        self.rollp.setGeometry(QtCore.QRect(80, 79, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.rollp.setFont(font)
        self.rollp.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.rollp.setObjectName("rollp")
        self.rolli = QtWidgets.QLabel(self.mainVals)
        self.rolli.setGeometry(QtCore.QRect(250, 80, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.rolli.setFont(font)
        self.rolli.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.rolli.setObjectName("rolli")
        self.rolld = QtWidgets.QLabel(self.mainVals)
        self.rolld.setGeometry(QtCore.QRect(420, 80, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.rolld.setFont(font)
        self.rolld.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.rolld.setObjectName("rolld")
        self.roll_P = QtWidgets.QLineEdit(self.mainVals)
        self.roll_P.setGeometry(QtCore.QRect(110, 80, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.roll_P.setFont(font)
        self.roll_P.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.roll_P.setInputMask("")
        self.roll_P.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_P.setObjectName("roll_P")
        self.roll_I = QtWidgets.QLineEdit(self.mainVals)
        self.roll_I.setGeometry(QtCore.QRect(280, 81, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.roll_I.setFont(font)
        self.roll_I.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.roll_I.setInputMask("")
        self.roll_I.setCursorPosition(4)
        self.roll_I.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_I.setDragEnabled(False)
        self.roll_I.setObjectName("roll_I")
        self.roll_D = QtWidgets.QLineEdit(self.mainVals)
        self.roll_D.setGeometry(QtCore.QRect(450, 81, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.roll_D.setFont(font)
        self.roll_D.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.roll_D.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.roll_D.setInputMask("")
        self.roll_D.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_D.setObjectName("roll_D")
        self.depth_I = QtWidgets.QLineEdit(self.mainVals)
        self.depth_I.setGeometry(QtCore.QRect(280, 251, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(18)
        self.depth_I.setFont(font)
        self.depth_I.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.depth_I.setInputMask("")
        self.depth_I.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_I.setObjectName("depth_I")
        self.depth_D = QtWidgets.QLineEdit(self.mainVals)
        self.depth_D.setGeometry(QtCore.QRect(450, 251, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(16)
        self.depth_D.setFont(font)
        self.depth_D.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.depth_D.setInputMask("")
        self.depth_D.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_D.setObjectName("depth_D")
        self.depthp = QtWidgets.QLabel(self.mainVals)
        self.depthp.setGeometry(QtCore.QRect(80, 249, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.depthp.setFont(font)
        self.depthp.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.depthp.setObjectName("depthp")
        self.depthd = QtWidgets.QLabel(self.mainVals)
        self.depthd.setGeometry(QtCore.QRect(420, 250, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.depthd.setFont(font)
        self.depthd.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.depthd.setObjectName("depthd")
        self.depthi = QtWidgets.QLabel(self.mainVals)
        self.depthi.setGeometry(QtCore.QRect(250, 250, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.depthi.setFont(font)
        self.depthi.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.depthi.setObjectName("depthi")
        self.depth_P = QtWidgets.QLineEdit(self.mainVals)
        self.depth_P.setGeometry(QtCore.QRect(110, 250, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(18)
        self.depth_P.setFont(font)
        self.depth_P.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.depth_P.setInputMask("")
        self.depth_P.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_P.setObjectName("depth_P")
        self.pitch_I = QtWidgets.QLineEdit(self.mainVals)
        self.pitch_I.setGeometry(QtCore.QRect(280, 411, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(18)
        self.pitch_I.setFont(font)
        self.pitch_I.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.pitch_I.setInputMask("")
        self.pitch_I.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch_I.setObjectName("pitch_I")
        self.pitch_D = QtWidgets.QLineEdit(self.mainVals)
        self.pitch_D.setGeometry(QtCore.QRect(450, 411, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(18)
        self.pitch_D.setFont(font)
        self.pitch_D.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.pitch_D.setInputMask("")
        self.pitch_D.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch_D.setObjectName("pitch_D")
        self.pitchp = QtWidgets.QLabel(self.mainVals)
        self.pitchp.setGeometry(QtCore.QRect(80, 410, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pitchp.setFont(font)
        self.pitchp.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pitchp.setObjectName("pitchp")
        self.pitchd = QtWidgets.QLabel(self.mainVals)
        self.pitchd.setGeometry(QtCore.QRect(420, 410, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pitchd.setFont(font)
        self.pitchd.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pitchd.setObjectName("pitchd")
        self.pitchi = QtWidgets.QLabel(self.mainVals)
        self.pitchi.setGeometry(QtCore.QRect(250, 410, 20, 41))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pitchi.setFont(font)
        self.pitchi.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pitchi.setObjectName("pitchi")
        self.pitch_P = QtWidgets.QLineEdit(self.mainVals)
        self.pitch_P.setGeometry(QtCore.QRect(110, 410, 90, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(18)
        self.pitch_P.setFont(font)
        self.pitch_P.setStyleSheet("background-color: rgb(13, 110, 8);\n"
"color: rgb(255, 255, 255);")
        self.pitch_P.setInputMask("")
        self.pitch_P.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch_P.setObjectName("pitch_P")
        self.PIDApply = QtWidgets.QPushButton(self.mainVals)
        self.PIDApply.setGeometry(QtCore.QRect(130, 550, 381, 71))
        font = QtGui.QFont()
        font.setFamily("8-bit Operator+ 8")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(25)
        self.PIDApply.setFont(font)
        self.PIDApply.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
" font-size: 40px;\n"
"  font-weight: 200;\n"
"  letter-spacing: 1px;\n"
"  padding: 13px 50px 13px;\n"
"  outline: 0;\n"
"  border: 3px solid;\n"
"border-radius:15px;\n"
"\n"
"    border-color: rgb(255, 255, 255);\n"
"\n"
"  position: relative;\n"
"  background-color: rgba(0, 255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"position :-5px 5px;\n"
"label.left : -5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.502, y2:0.517091, stop:0 rgba(13, 110, 8, 255), stop:1 rgba(36, 225, 42, 255));\n"
"\n"
"\n"
"}")
        self.PIDApply.setIconSize(QtCore.QSize(100, 100))
        self.PIDApply.setObjectName("PIDApply")
        self.PIDLabel = QtWidgets.QLabel(self.mainVals)
        self.PIDLabel.setGeometry(QtCore.QRect(140, 560, 381, 71))
        self.PIDLabel.setStyleSheet("QLabel{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.502, y2:0.517091, stop:0 rgba(36, 225, 42, 255), stop:1 rgba(13, 110, 8, 255));\n"
"  width: 100%;\n"
"  z-index: -1;\n"
"  position: relative;\n"
"  height: 100%;\n"
"  top: 7px;\n"
"  left: 7px;\n"
"border-radius:15px;\n"
"\n"
"\n"
"}\n"
"QLabel::Hover{\n"
"  top: 0px;\n"
"  left: 0px;\n"
"}\n"
"")
        self.PIDLabel.setText("")
        self.PIDLabel.setObjectName("PIDLabel")
        self.depth.raise_()
        self.roll.raise_()
        self.pitch.raise_()
        self.rollp.raise_()
        self.rolli.raise_()
        self.rolld.raise_()
        self.roll_P.raise_()
        self.roll_I.raise_()
        self.roll_D.raise_()
        self.depth_I.raise_()
        self.depth_D.raise_()
        self.depthp.raise_()
        self.depthd.raise_()
        self.depthi.raise_()
        self.depth_P.raise_()
        self.pitch_I.raise_()
        self.pitch_D.raise_()
        self.pitchp.raise_()
        self.pitchd.raise_()
        self.pitchi.raise_()
        self.pitch_P.raise_()
        self.PIDLabel.raise_()
        self.PIDApply.raise_()
        pidMenu.addTab(self.mainVals, "")

        self.retranslateUi(pidMenu)
        pidMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pidMenu)

    def retranslateUi(self, pidMenu):
        _translate = QtCore.QCoreApplication.translate
        pidMenu.setWindowTitle(_translate("pidMenu", "PIDC Settings"))
        self.depth.setText(_translate("pidMenu", "Depth"))
        self.roll.setText(_translate("pidMenu", "Roll"))
        self.pitch.setText(_translate("pidMenu", "Pitch"))
        self.rollp.setText(_translate("pidMenu", "P:"))
        self.rolli.setText(_translate("pidMenu", "I"))
        self.rolld.setText(_translate("pidMenu", "D:"))
        self.roll_P.setText(_translate("pidMenu", "0"))
        self.roll_I.setText(_translate("pidMenu", "1234"))
        self.roll_D.setText(_translate("pidMenu", "5"))
        self.depth_I.setText(_translate("pidMenu", "0"))
        self.depth_D.setText(_translate("pidMenu", "0"))
        self.depthp.setText(_translate("pidMenu", "P:"))
        self.depthd.setText(_translate("pidMenu", "D:"))
        self.depthi.setText(_translate("pidMenu", "I"))
        self.depth_P.setText(_translate("pidMenu", "0"))
        self.pitch_I.setText(_translate("pidMenu", "0"))
        self.pitch_D.setText(_translate("pidMenu", "0"))
        self.pitchp.setText(_translate("pidMenu", "P:"))
        self.pitchd.setText(_translate("pidMenu", "D:"))
        self.pitchi.setText(_translate("pidMenu", "I"))
        self.pitch_P.setText(_translate("pidMenu", "0"))
        self.PIDApply.setText(_translate("pidMenu", "APPLY"))
        pidMenu.setTabText(pidMenu.indexOf(self.mainVals), _translate("pidMenu", "RDDPMC Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pidMenu = QtWidgets.QTabWidget()
    ui = Ui_pidMenu()
    ui.setupUi(pidMenu)
    pidMenu.show()
    sys.exit(app.exec_())

